version: "3.8"

services:
  healthchecks:
    image: linuxserver/healthchecks:3.2.20240209
    container_name: healthchecks
    restart: always
    networks:
      - datakata-network
    volumes:
      - ./healthchecks_data:/config
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  datakata-network:
    external: true
