version: "3.8"
services:
  website_cyberpony:
    image: ghcr.io/wol4aravio/cyberpony:0.0.6
    labels:
      env: dev
    networks:
      - datakata-network
    environment:
      - HEALTHCHECK_URL=${HEALTHCHECK_URL}
    healthcheck:
      test: (curl --fail $HEALTHCHECK_URL && curl --fail http://0.0.0.0:3000/health) || exit 1
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      placement:
        constraints:
          - "node.labels.env.prod==true"
      resources:
        reservations:
          cpus: "0.2"
          memory: 128mb
        limits:
          cpus: "0.5"
          memory: 256mb

networks:
  datakata-network:
    external: true
