version: "3.8"
services:
  healthchecks:
    image: healthchecks/healthchecks:v3.2
    container_name: healthchecks
    networks:
      - datakata-network
    environment:
      - DB=sqlite
      - DB_NAME=/data/hc.sqlite
      - DEBUG=False
      - SITE_ROOT=http://localhost:8000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 64M
      placement:
        constraints:
          - node.role == manager

networks:
  datakata-network:
    external: true
