version: "3.8"

services:
  healthchecks:
    image: linuxserver/healthchecks:3.2.20240209
    container_name: healthchecks
    restart: always
    networks:
      - datakata-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./healthchecks_data:/config
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 64M
      placement:
        constraints:
          - node.role == manager

networks:
  datakata-network:
    external: true
