version: "3.8"
services:
  website_dev_bigdatawhale:
    image: ghcr.io/wol4aravio/bigdatawhale:dev-0.0.1
    labels:
      env: dev
    networks:
      - datakata-network
    healthcheck:
      test: curl --fail http://0.0.0.0:3000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.env.dev==true"
      resources:
        reservations:
          cpus: "0.2"
          memory: 128mb
        limits:
          cpus: "0.5"
          memory: 256mb

networks:
  datakata-network:
    external: true
