name: Image Build

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Compose build suffix
        run: |
          echo "Discovering the environment stage:"
          if [[ ${{ github.ref == 'refs/heads/dev' }} ]]; then
            echo "BUILD_SUFFIX=dev" >> $GITHUB_ENV
          fi
          echo "Environment stage is set:"
          echo "${{ GITHUB_ENV }}"
