name: Image Build

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUILD_SUFFIX: ${{ github.ref == 'refs/heads/master' && '' || 'dev' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Compose build suffix
        run: |
          echo "${{ env.BUILD_SUFFIX }}"
