name: Image Build

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RUNTIME_ENVIRONMENT: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
  BUILD_SUFFIX: ${{ github.ref == 'refs/heads/master' && '' || 'dev-' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get env vars
        uses: cardinalby/export-env-action@v2
        with:
          envFile: 'env_files/panovskiy.env'
          expand: 'true'
      - name: Build panovskiy.ru website
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/web/Dockerfile
          target: panovskiy
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/wol4aravio/${{ env.WEBSITE }}:${{ env.BUILD_SUFFIX }}${{ env.VERSION }}
          labels: |
            website=${{ env.WEBSITE }}
            env=${{ env.RUNTIME_ENVIRONMENT }}

