name: Image Build

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Compose build suffix
        if: github.ref == 'refs/heads/master'
        env:
          BUILD_SUFFIX: ""
        else:
        env:
          BUILD_SUFFIX: "dev"
      - name: Test
        run: |
          echo $BUILD_SUFFIX
